env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  'no-console': 0
  'no-undef': 0
  'no-unused-vars':
    - warn
  '@typescript-eslint/indent':
    - error
    - tab
  '@typescript-eslint/class-name-casing': 0
  '@typescript-eslint/interface-name-prefix': 0
  '@typescript-eslint/camelcase': 0
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/ban-ts-ignore': 0
