enum ActivityType {
	University
	Faculty
	Course
	Groups
}

enum AppointmentType {
	Lecture
	Exercise
	Training
}

enum Weekday {
	Monday
	Tuesday
	Wednesday
	Thursday
	Friday
	Saturday
	Sunday
}

enum DuringType {
	WinterSemester
	SummerSemester
	Always
}