enum ActivityType {
	UNIVERSITY
	FACULTY
	COURSE
	GROUPS
}

enum AppointmentType {
	LECTURE
	EXERCISE
	TRAINING
}

enum Weekday {
	MONDAY
	TUESDAY
	WEDNESDAY
	THURSDAY
	FRIDAY
	SATURDAY
	SUNDAY
}

enum DuringType {
	WINTER_SEMESTER
	SUMMER_SEMESTER
	ALWAYS
}