input AppointmentInput {
	type: AppointmentType!
	on: Weekday
	from: GraphQLDateTime!
	to: GraphQLDateTime!
	activity: ID!
}

input ActivityInput {
	type: ActivityType!
	name: String!
	exclusive: Boolean!
	during: DuringType!
	parent: ID!
}

input LoginInput {
	username: String!
	password: String!
}
