input AppointmentInput {
	type: AppointmentType!
	schedule: ScheduleInput!
	activity: ID!
}

input ScheduleInput {
	on: Weekday
	during: DuringType
	from: GraphQLDateTime!
	to: GraphQLDateTime!
}

input ActivityInput {
	type: ActivityType!
	exclusive: Boolean!
	parent: ID!
}

input LoginInput {
	username: String!
	password: String!
}
