#import "./enums.gql"
#import "./scalars.gql"
#import "./inputs.gql"
#import "./types.gql"

type Query {
    activities(parentId: ID!): [Activity!]!
    user(userId: ID!): User!
}

type Mutation {
    addAppointment(input: AppointmentInput): Appointment!
    addActivity(input: ActivityInput): Activity!
    login(input: LoginInput): User!
}
